import Head from "next/head";
import Image from "next/image";
import "bootstrap/dist/css/bootstrap.min.css";

console.log = () => {};
console.error = () => {};
console.debug = () => {};

export default function Home() {
  return (
    <>
      <Head>
        {/* <title>DesignPerfecto</title> */}
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <script
          src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"
          integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ"
          crossorigin="anonymous"
        ></script>

        <link rel="shortcut icon" href="/images/favicon.ico" />
        {/* <link rel="icon" href="/apple-touch-icon.ico" /> */}
        <link rel="icon" href="/images/favicon.ico" />

        {/* <link
          rel="apple-touch-icon"
          sizes="180x180"
          // href="/apple-touch-icon.png"
          href="/public/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          // href="/favicon-32x32.png"
          href="/public/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          // href="/favicon-16x16.png"
          href="/public/favicon-16x16.png"
        /> */}
        {/* <link rel="manifest" href="/site.webmanifest" />
        <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5" /> */}
      </Head>
      {/* <CollapsibleExample /> */}
      {/* <h1>
        Fonts Knowledge Welcome to our library of original guides to the world
        of typography, which the Google Fonts team is producing in collaboration
        with typographic experts from around the world. Google Fonts Knowledge
        enables designers and developers of all skill sets to choose and use
        type with purpose.
      </h1> */}
    </>
  );
}
